### ISSUE TITLE
Field descriptions/examples and SQLAlchemyAutoSchema

### ISSUE THREAD

**Issue by BenGatewood** [marshmallow-code/flask-smorest#156] opened 2020-06-01 07:03 UTC
Hey All,

I'm making heavy use of **SQLAlchemyAutoSchema** as my project has a large number of separate databases where there are common tables between DBs but those tables have different structures (long story). I'd really, really like to be able to pass a _description_ and _example_ keyword argument to each field for inclusion in our OAS api-spec but unfortunately I can't use this [recipe](https://marshmallow-sqlalchemy.readthedocs.io/en/latest/recipes.html#overriding-generated-fields) as by the time an instance of the class is created, flask-smorest has already generated the documentation so my changes don't get included. 

I'm looking for suggestions for the best way to achieve this if anyone's got any?

**Comment by sloria** [comment] 2020-06-01 14:08
apispec does have support for [descriptions](https://apispec.readthedocs.io/en/latest/api_ext.html?highlight=description#module-apispec.ext.marshmallow) and [examples](https://apispec.readthedocs.io/en/latest/api_core.html?highlight=example#apispec.core.Components.example), though I'm unsure offhand how to resolve the issue with flask-smorest. I've transferred this to the flask-smorest repo so perhaps @lafrech can help.

**Comment by lafrech** [comment] 2020-06-01 15:25
My experience with sqlalchemy is limited.

I can't really answer without more details.

> by the time an instance of the class is created, flask-smorest has already generated the documentation so my changes don't get included

This sounds strange.

You may want to have a look at this example: https://github.com/lafrech/flask-smorest-sqlalchemy-example.

**Comment by lafrech** [comment] 2020-06-01 15:27
> I've transferred this to the flask-smorest repo so perhaps @lafrech can help.

No pb @sloria, I don't watch marshmallow-sqlalchemy repo.

I do follow marshmallow questions on SO and answer whenever I can but I generally don't answer sqlalchemy questions because most of the times, either it is poorly written, either the OP has been doing his job searching by himself and he knows more than I do already.

**Comment by BenGatewood** [comment] 2020-06-02 00:19
Thanks all for the responses.

Yeah, adding descriptions/examples to a basic schema is straightforward and if I statically define all my schemas that works perfectly fine - no problems at all. Thing is, I really want to avoid having to statically define all my schemas due to the aforementioned multiple DBs/differing tables thing.

What I really hoped to be able to do was something like:

```py class MyAutoSchema(ma.SQLAlchemyAutoSchema):

    class Meta:
        table = db.table

    descriptions = get_descriptions()

    for field in _declared_fields  # <-- I know I can't access this here/yet
        field = ma.auto_field(description = descriptions[field]["description"],
                              example = descriptions[field]["example"])```

**Comment by BenGatewood** [comment] 2020-06-02 00:23
> My experience with sqlalchemy is limited.
> 
> I can't really answer without more details.
> 
> > by the time an instance of the class is created, flask-smorest has already generated the documentation so my changes don't get included
> 
> This sounds strange.
> 
> You may want to have a look at this example: https://github.com/lafrech/flask-smorest-sqlalchemy-example.

Thanks @lafrech but I think all the schemas in that example are statically defined? Unless you mean using this [override](https://github.com/lafrech/flask-smorest-sqlalchemy-example/blob/817ea6987119a37e6a8e1b158b2b79dcc6df3b62/team_manager/extensions/api/__init__.py#L32) to do it?

**Comment by lafrech** [comment] 2020-06-02 05:43
Nope, nothing to do with this override.

From flask-smorest POV, I don't see the difference between your code above iterating on declared fields and the exemple you point to in the docs. I mean you can create the SQLAlchemy schema, then generate the associated marshmallow schema, then customize it anyway you like, then pass it to flask-smorest.

AFAIU, this is a marshmallow-sqlalchemy issue. But I may be missing something.

What would be nice would be to pass field metadata (description and example kwargs) from sqlalchemy model to generated marshmallow schema. Maybe it already does it. Cant' test right now.

**Comment by BenGatewood** [comment] 2020-06-02 05:54
> Nope, nothing to do with this override.
> 
> From flask-smorest POV, I don't see the difference between your code above iterating on declared fields and the exemple you point to in the docs. I mean you can create the SQLAlchemy schema, then generate the associated marshmallow schema, then customize it anyway you like, then pass it to flask-smorest.

Hmm. OK. Maybe it's as simple as me not comprehending if/how I can access the ** _declared_fields** from the main class body?

> AFAIU, this is a marshmallow-sqlalchemy issue. But I may be missing something.
> 
> What would be nice would be to pass field metadata (description and example kwargs) from sqlalchemy model to generated marshmallow schema. Maybe it already does it. Cant' test right now.

That would be nice actually. I'll have another look myself to see if I missed something last time I looked. Thanks again!

**Comment by lafrech** [comment] 2020-06-02 06:04
> Hmm. OK. Maybe it's as simple as me not comprehending if/how I can access the ** _declared_fields** from the main class body?

I'm not saying it is easy or even the best thing to do. Just saying it is unrelated to flask-smorest as all of this happens before the schema is passed to the framework.

You should be able to iterate on the fields and patch them to add desired metadata, but this sucks. Ideally, you'd be able to have the metadata passed when the field is built, in marshmallow-sqlalchemy. It is worth investigating there, and suggesting the feature if it doesn't exist.

**Comment by BenGatewood** [comment] 2020-06-02 06:07
> > Hmm. OK. Maybe it's as simple as me not comprehending if/how I can access the ** _declared_fields** from the main class body?
> 
> I'm not saying it is easy of even the best thing to do. Just saying it is unrelated to flask-smorest as all of this happens before the schema is passed to the framework.
> 
> You should be able to iterate on the fields and patch them to add desired metadata, but this sucks. Ideally, you'd be able to have the metadata passed when the field is built, in marshmallow-sqlalchemy. It is worth investigating there, and suggesting the feature if it doesn't exist.

Yes. Makes sense. I'll go have a look - thanks!

**Comment by BenGatewood** [comment] 2020-06-03 04:59
For completeness/random googlers, this is actually pretty trivial to achieve with a decorator:

```py 
def schema_update(cls):

    field_extras = get_extra_metadata()

    for k, v in cls._declared_fields.items():
        if k in field_extras:
            v.metadata = {"description": field_extras[k][0], "example": field_extras[k][1]}
    return cls
```

Then just wrap your marshmallow schema defs:

```py 
@schema_update
class MyAutoSchema(SQLAlchemyAutoSchema):
    class Meta:
        table = my_db.table
```

Still going to have a nose around when I get a chance to see if there's a more native way to do it

**Comment by lafrech** [comment] 2021-04-29 08:04
I'm closing this as it is not a flask-smorest issue.

IIUC, this should work fine in marshmallow-SQLAlchemy already, so I'm not sure what the problem is/was.

Beware that marshmallow now expects metadata to be passed as `metadata` dict, not as kwargs. marshmallow-sqlalchemy has just been updated to respect that.

**Closed as completed by lafrech** 2021-04-29 08:04 UTC
Labels: question
