### ISSUE TITLE
Using a dictionary as a Schema

### ISSUE THREAD

**Issue by aprilahijriyan** [marshmallow-code/flask-smorest#238] opened 2021-04-08 01:19 UTC
i get error when using dictionary as Schema.

The dictionary that I use:

```python
@use_kwargs({"limit": fields.Integer(), "offset": fields.Integer()}, location="query")
```

the following is the error log.

```
Traceback (most recent call last):
  File "/home/Projects/zemfrog/venv/bin/flask", line 8, in <module>
    sys.exit(main())
  File "/home/Projects/zemfrog/venv/lib/python3.6/site-packages/flask/cli.py", line 967, in main
    cli.main(args=sys.argv[1:], prog_name="python -m flask" if as_module else None)
  File "/home/Projects/zemfrog/venv/lib/python3.6/site-packages/flask/cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/home/Projects/zemfrog/venv/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/Projects/zemfrog/venv/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/Projects/zemfrog/venv/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/Projects/zemfrog/venv/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/Projects/zemfrog/venv/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/Projects/zemfrog/venv/lib/python3.6/site-packages/flask/cli.py", line 425, in decorator
    with __ctx.ensure_object(ScriptInfo).load_app().app_context():
  File "/home/Projects/zemfrog/venv/lib/python3.6/site-packages/flask/cli.py", line 392, in load_app
    app = locate_app(self, import_name, None, raise_if_not_found=False)
  File "/home/Projects/zemfrog/venv/lib/python3.6/site-packages/flask/cli.py", line 240, in locate_app
    __import__(module_name)
  File "/home/Projects/zemfrog/demo/app/wsgi.py", line 3, in <module>
    app = create_app("wsgi")
  File "/home/Projects/zemfrog/zemfrog/app.py", line 79, in create_app
    loader(app)
  File "/home/Projects/zemfrog/zemfrog/loaders/api.py", line 39, in loader
    smorest.register_blueprint(bp)
  File "/home/Projects/zemfrog/venv/lib/python3.6/site-packages/flask_smorest/__init__.py", line 87, in register_blueprint
    blp.register_views_in_doc(self, self._app, self.spec)
  File "/home/Projects/zemfrog/venv/lib/python3.6/site-packages/flask_smorest/blueprint.py", line 204, in register_views_in_doc
    spec.path(rule=rule, operations=doc, parameters=parameters)
  File "/home/Projects/zemfrog/venv/lib/python3.6/site-packages/apispec/core.py", line 304, in path
    self.clean_operations(operations)
  File "/home/Projects/zemfrog/venv/lib/python3.6/site-packages/apispec/core.py", line 407, in clean_operations
    operation["parameters"] = self.clean_parameters(operation["parameters"])
  File "/home/Projects/zemfrog/venv/lib/python3.6/site-packages/apispec/core.py", line 364, in clean_parameters
    f"Missing keys {missing_attrs} for parameter"
apispec.exceptions.InvalidParameterError: Missing keys ['name'] for parameter
```

**Comment by lafrech** [comment] 2021-04-08 06:34
Duplicate of #180.

**Closed as completed by lafrech** 2021-04-08 06:34 UTC
