### ISSUE TITLE
Keyworded arguments

### ISSUE THREAD

**Issue by BnGx** [marshmallow-code/flask-smorest#226] opened 2021-02-08 19:59 UTC
Currently the _ArgumentsMixin_ class implements only the _arguments_ function which returns the result of ``ARGUMENTS_PARSER.use_args``

It would be better to implement the _kwarguments_ function as well by returning the result of ``ARGUMENTS_PARSER.use_kwargs``

**Comment by lafrech** [comment] 2021-02-08 20:09
Duplicate of #47.

**Closed as completed by lafrech** 2021-02-08 20:09 UTC
