### ISSUE TITLE
Serializing flask response

### ISSUE THREAD

**Issue by mekanix** [marshmallow-code/flask-smorest#31] opened 2018-11-25 17:04 UTC
I need to set cookies with on some endpoints. Just returning `jsonify({ 'key': 'value' })` does not get serialized. Is there a way to set a cookie in the response together with the "normal" endpoint response?

**Comment by lafrech** [comment] 2018-11-29 20:35
Can you elaborate on your use case?

Since this is about REST APIs, I assume it is an authentication cookie, right?

Do you want to set it from the view function? From a custom authentication decorator?

**Comment by mekanix** [comment] 2018-11-30 05:17
Yes, it's auth cookie. So, with flask_restplus this is the code I used: https://github.com/mekanix/backend-startkit/blob/master/application/api/auth.py#L21-L64. Something I tried to achieve with flask_rest_api is this: https://github.com/mekanix/backend-startkit/blob/feature/rest-api/application/api/auth.py#L24-L68. The problem is that frontend says length of response is wrong (I suppose I'm overwriting something).

**Comment by lafrech** [comment] 2019-02-12 20:08
I don't see anything blocking you from setting a cookie from a decorator.

However, setting a cookie from a view function is currently impossible because by design of the `response` method, the view function can not return a flask `Response` object. This is discussed in https://github.com/Nobatek/flask-rest-api/pull/22.

IIUC, the `return resp.get_json()` in your code means you're returning only the json body of the response and not the cookies.

**Comment by mekanix** [comment] 2019-02-13 12:30
Than decorator is the right place. :) Can you please post the code snippet to achieve it? The code I linked to is not the way I have to solve it, it just the closest I've got to setting the cookie, so feel free to just ignore it.

**Comment by lafrech** [comment] 2019-02-13 14:38
I have no available snippet and no time for this right now.

You might find the conversation in #36 interesting, especially [this comment](https://github.com/Nobatek/flask-rest-api/issues/36#issuecomment-460826257).

**Comment by lafrech** [comment] 2019-04-11 10:41
Closing this for now. Feel free to comment if you're still stuck on this.

**Closed as completed by lafrech** 2019-04-11 10:41 UTC
Labels: question
