### ISSUE TITLE
Nested blueprints don't generate docs

### ISSUE THREAD

**Issue by Cnoor0171** [marshmallow-code/flask-smorest#333] opened 2022-03-13 21:59 UTC
Flask blueprints can be registered on another blueprint by calling `register_blueprint` method of the `flask.Blueprint` class. The `flask_smorest.Blueprint` also allows for this since it inherits from `flask.Blueprint`. However, the documentation is only generated for blueprints directly registered on the `Api` instance. The nested blueprints work if you send a request, but don't generate any docs.

[Flask documentation on nested blueprints](https://flask.palletsprojects.com/en/2.0.x/blueprints/#nesting-blueprints)

Example:
```python


from flask import Flask
from flask.views import MethodView
import marshmallow as ma
from flask_smorest import Api, Blueprint


app = Flask(__name__)
app.config["API_TITLE"] = "My API"
app.config["API_VERSION"] = "v1"
app.config["OPENAPI_VERSION"] = "3.0.2"
app.config["OPENAPI_URL_PREFIX"] = "/"
app.config["OPENAPI_SWAGGER_UI_PATH"] = "/swagger-ui"
app.config["OPENAPI_SWAGGER_UI_URL"] = "https://cdn.jsdelivr.net/npm/swagger-ui-dist/"
api = Api(app)

class PetSchema(ma.Schema):
    id = ma.fields.Int(dump_only=True)
    name = ma.fields.String()

blp = Blueprint("pets", "pets", url_prefix="/pets", description="Operations on pets")

@blp.route("/")
class Pets(MethodView):
    @blp.response(200, PetSchema(many=True))
    def get(self):
        """List pets"""
        return [{"id": 1, "name": "Cujo"}]


parent_blp = Blueprint("pets_par", "pets_par")
parent_blp.register_blueprint(blp)
api.register_blueprint(parent_blp)

app.run(host="0.0.0.0", port=9050)
```

If you run the above app and navigate to `http://localhost:9050/pets/`, you'll get `[{"id":1,"name":"Cujo"}]`, but the swagger UI looks like

<img width="1127" alt="image" src="https://user-images.githubusercontent.com/33206267/158080988-9b271089-daa6-4ab7-80e1-b422493a2901.png">

**Comment by lafrech** [comment] 2022-03-13 22:14
Yup, known issue. Duplicate of #261.

**Closed as completed by lafrech** 2022-03-13 22:14 UTC
